title: valkyrie
description: "Survive a world born to violence."
baseurl: ""
url: "http://devynspencer.github.io"

twitter_username: devynspencer
github_username: devynspencer
# Build settings
permalink: pretty
markdown: kramdown
