title: Valkyrie, a reimagining of Arma
description: Arma 3 modules designed around facilitating a rich, dynamically-generated open world adventures. Experience a grittier, engaging version of Altis that adapts to your play style.
baseurl: "valkyrie"
url: "http://devynspencer.github.io"

twitter_username: devynspencer
github_username:  devynspencer

# Build settings
markdown: kramdown
