/*

  file:    population\pools\objects.sqf
  author:  http://devynspencer.github.io/valkrie
  about:   Provides collections of similar objects to randomly generate from
  example:

  v_construction = [
    "Land_Bricks_V1_F",

    ...

    "Land_WheelCart_F",
    "Land_WoodenBox_F",
    "Land_WorkStand_F"
];

*/

/*
v_civilianDebris_xs = [
Land_ButaneCanister_F
Land_ButaneTorch_F
Land_CanOpener_F
Land_DuctTape_F
Land_FireExtinguisher_F
Land_GasCanister_F
Land_GasCooker_F
Land_Matches_F
Land_MetalWire_F
Land_Shovel_F
Land_Pallets_stack_F
Land_PortableLight_single_F
Land_PortableLight_double_F
Land_BakedBeans_F
Land_BottlePlastic_V2_F
Land_Canteen_F
Land_CerealsBox_F
Land_PowderedMilk_F
Land_RiceBox_F
Land_Antibiotic_F
Land_Bandage_F
Land_BloodBag_F
Land_Defibrillator_F
Land_DisinfectantSpray_F
Land_HeatPack_F
Land_PainKillers_F
Land_VitaminBottle_F
Land_WaterPurificationTablets_F

v_civilianDebris_s
Land_BarrelEmpty_grey_F
Land_BarrelSand_grey_F
Land_BarrelTrash_grey_F
Land_BarrelWater_grey_F
Land_CrabCages_F
Land_FishingGear_01_F
Land_FishingGear_02_F
Land_Atm_01_F // only near buildings in cities
Land_Atm_02_F // only near buildings in cities
Land_Bench_01_F // near buildings or roads
Land_Bench_02_F // near buildings or roads
];

v_electronics = [
Land_ExtensionCord_F
Land_FloodLight_F
Land_FMradio_F
Land_HandyCam_F
Land_Laptop_F
Land_Laptop_unfolded_F
Land_MobilePhone_old_F
Land_MobilePhone_smart_F
Land_Portable_generator_F
Land_PortableLongRangeRadio_F
Land_SatellitePhone_F
Land_SurvivalRadio_F
Land_Laptop_device_F
];

v_wrecks = [
Land_Scrap_MRAP_01_F
Land_ScrapHeap_1_F
Land_ScrapHeap_2_F
Land_UWreck_FishingBoat_F
Land_UWreck_Heli_Attack_02_F
Land_UWreck_MV22_F
Land_Wreck_BMP2_F
Land_Wreck_BRDM2_F
Land_Wreck_Car_F
Land_Wreck_Car2_F
Land_Wreck_Car3_F
Land_Wreck_CarDismantled_F
Land_Wreck_Heli_Attack_01_F
Land_Wreck_Heli_Attack_02_F
Land_Wreck_HMMWV_F
Land_Wreck_Hunter_F
Land_Wreck_Offroad_F
Land_Wreck_Offroad2_F
Land_Wreck_Plane_Transport_01_F
Land_Wreck_Skodovka_F
Land_Wreck_Slammer_F
Land_Wreck_Slammer_hull_F
Land_Wreck_Slammer_turret_F
Land_Wreck_T72_hull_F
Land_Wreck_T72_turret_F
Land_Wreck_Traw_F
Land_Wreck_Traw2_F
Land_Wreck_Truck_dropside_F
Land_Wreck_Truck_F
Land_Wreck_UAZ_F
Land_Wreck_Ural_F
Land_Wreck_Van_F
];

// split these into small/medium/large
// could use is_type(ammo_crate_whatever) or similar
v_containers = [
Box_NATO_WpsSpecial_F
Box_NATO_Grenades_F
Box_East_WpsSpecial_F
Box_East_Grenades_F
Box_IND_WpsSpecial_F
Box_IND_Grenades_F
Box_NATO_Wps_F
Box_NATO_WpsSpecial_F
Box_NATO_Ammo_F
Box_East_Wps_F
Box_East_WpsSpecial_F
Box_East_Ammo_F
C_supplyCrate_F
Box_NATO_Wps_F
Box_NATO_WpsSpecial_F
Box_NATO_WpsLaunch_F
Box_NATO_Ammo_F
Box_NATO_AmmoOrd_F
Box_NATO_Grenades_F
Box_NATO_Support_F
Box_NATO_AmmoVeh_F
Box_East_Wps_F
Box_East_WpsSpecial_F
Box_East_WpsLaunch_F
Box_East_Ammo_F
Box_East_AmmoOrd_F
Box_East_Grenades_F
Box_East_Support_F
Box_East_AmmoVeh_F
Box_IND_Wps_F
Box_IND_WpsSpecial_F
Box_IND_WpsLaunch_F
Box_IND_Ammo_F
Box_IND_AmmoOrd_F
Box_IND_Grenades_F
Box_IND_Support_F
Box_IND_AmmoVeh_F
Box_Ammo_F
Box_Wps_F
Land_Box_AmmoOld_F
Land_Box_AmmoD_F
B_supplyCrate_F
O_supplyCrate_F
IG_supplyCrate_F
B_AssaultPack_khk
B_AssaultPack_khk_holder
B_Fieldpack_oli_Ammo
B_Fieldpack_oli_Medic
B_Fieldpack_oli_Repair
B_Fieldpack_oli
B_AssaultPack_dgtl
B_Fieldpack_oli_AAR
B_AssaultPack_rgr
B_AssaultPack_rgr_AT
B_AssaultPack_rgr_Medic
B_AssaultPack_rgr_ReconMedic
B_AssaultPack_rgr_Repair
B_AssaultPack_sgg
B_AssaultPack_sgg_ReconExp
B_AssaultPack_sgg_ReconLAT
B_AssaultPack_blk
B_AssaultPack_blk_DiverExp
B_AssaultPack_cbr
B_AssaultPack_mcamo
B_AssaultPack_mcamo_AA
B_AssaultPack_mcamo_AAR
B_AssaultPack_mcamo_Ammo
B_AssaultPack_ocamo
B_Kitbag_mcamo
B_Kitbag_mcamo_Eng
B_Kitbag_sgg
B_Kitbag_cbr
B_Bergen_mcamo
B_Bergen_mcamo_AAA
B_Carryall_oli
B_Carryall_oli_AAT
B_Carryall_oli_Exp
B_Carryall_oli_AAA
B_Carryall_oli_Eng
B_Bergen_rgr
B_Bergen_rgr_AAT
B_Bergen_sgg
B_Bergen_sgg_Exp
B_Bergen_blk
B_FieldPack_khk
B_FieldPack_blk
B_FieldPack_blk_DiverExp
B_FieldPack_ocamo
B_FieldPack_ocamo_AA
B_FieldPack_ocamo_AAR
B_FieldPack_ocamo_Medic
B_FieldPack_ocamo_ReconMedic
B_FieldPack_oucamo
B_FieldPack_oucamo_AAR
B_FieldPack_oucamo_ReconExp
B_FieldPack_ocamo_Spotter
B_FieldPack_cbr
B_FieldPack_cbr_AAT
B_FieldPack_cbr_Ammo
B_FieldPack_cbr_Repair
B_Carryall_ocamo
B_Carryall_ocamo_AAA
B_Carryall_ocamo_Eng
B_Carryall_oucamo
B_Carryall_ocamo_Exp
B_Carryall_khk
B_Carryall_cbr
B_Carryall_cbr_AAT
B_OutdoorPack_blk
B_OutdoorPack_tan
B_OutdoorPack_blu
B_HuntingBackpack
B_AssaultPackG
B_AssaultPackG_AAR
B_AssaultPackG_Eng
B_BergenG
B_BergenG_Medic
B_BergenC_red
B_BergenC_grn
B_BergenC_blu
B_Parachute
Bag_Base
B_AssaultPack_Base
B_Kitbag_Base
B_Bergen_Base
B_FieldPack_Base
B_Carryall_Base
B_OutdoorPack_Base
B_BergenC_Base
B_Kitbag_rgr
];

v_camp = [
Land_Timbers_F
Land_WoodPile_F
Land_Campfire_F
Campfire_burning_F
Land_Camping_Light_off_F
Land_CampingChair_V1_F
Land_CampingChair_V1_folded_F
Land_CampingChair_V2_F
Land_CampingTable_F
Land_CampingTable_small_F
Land_FirePlace_F
FirePlace_burning_F
Land_Ground_sheet_F
Land_Ground_sheet_OPFOR_F
Land_Ground_sheet_blue_F
Land_Ground_sheet_folded_F
Land_Ground_sheet_folded_OPFOR_F
Land_Ground_sheet_folded_blue_F
Land_Ground_sheet_folded_khaki_F
Land_Ground_sheet_folded_yellow_F
Land_Ground_sheet_khaki_F
Land_Ground_sheet_yellow_F
Land_Pillow_F
Land_Pillow_camouflage_F
Land_Pillow_grey_F
Land_Pillow_old_F
Land_Sleeping_bag_F
Land_Sleeping_bag_blue_F
Land_Sleeping_bag_blue_folded_F
Land_Sleeping_bag_brown_F
Land_Sleeping_bag_brown_folded_F
Land_Sleeping_bag_folded_F
Land_Sun_chair_F
Land_Sun_chair_green_F
Land_Sunshade_F
Land_TentA_F
Land_TentDome_F
];

v_cityFurniture = [
Land_Bench_F
Land_CashDesk_F
Land_HeatPump_F
Land_ChairPlastic_F
Land_ChairWood_F
Land_Icebox_F
Land_Metal_rack_F
Land_Metal_rack_Tall_F
Land_Metal_wooden_rack_F
Land_Rack_F
Land_ShelvesMetal_F
Land_ShelvesWooden_blue_F
Land_TableDesk_F
];

v_construction = [
"Land_Bricks_V1_F",
"Land_Bricks_V2_F",
"Land_Bricks_V3_F",
"Land_Bricks_V4_F",
"Land_CinderBlocks_F",
"Land_Coil_F",
"Land_ConcretePipe_F",
"Land_IronPipes_F",
"Land_Pallet_F",
"Land_Pallet_vertical_F",
"Land_Pallets_F",
"Land_Pipes_large_F",
"Land_Pipes_small_F",
"Land_Scaffolding_F",
"Land_WheelCart_F",
"Land_WoodenBox_F",
"Land_WorkStand_F",
Land_BarrelEmpty_F
Land_BarrelSand_F
Land_BarrelTrash_F
Land_BarrelWater_F
Land_Bucket_F
Land_Bucket_clean_F
Land_Bucket_painted_F
Land_BucketNavy_F
Land_CanisterFuel_F
Land_CanisterOil_F
Land_CanisterPlastic_F
Land_MetalBarrel_empty_F
MetalBarrel_burning_F
Land_MetalBarrel_F
Land_WaterBarrel_F
Land_WaterTank_F
Land_Axe_F
Land_Axe_fire_F
Land_DrillAku_F
Land_DustMask_F
Land_File_F
Land_Gloves_F
Land_Grinder_F
Land_Hammer_F
Land_Meter3m_F
Land_MultiMeter_F
Land_Pliers_F
Land_Saw_F
Land_Screwdriver_V1_F
Land_Screwdriver_V2_F
Land_Wrench_F
Land_Pallets_stack_F
Land_PortableLight_single_F
Land_PortableLight_double_F
Land_GarbageContainer_closed_F
Land_GarbageContainer_open_F
Land_BarrelEmpty_grey_F
Land_BarrelSand_grey_F
Land_BarrelTrash_grey_F
Land_BarrelWater_grey_F
Land_GarbageBarrel_01_F
Land_FieldToilet_F
Land_ToiletBox_F
];

v_trash = [
"Land_Garbage_line_F",
"Land_Garbage_square3_F",
"Land_Garbage_square5_F",
"Land_GarbageBags_F",
"Land_GarbagePallet_F",
"Land_GarbageWashingMachine_F",
"Land_JunkPile_F",
"Land_Tyre_F",
"Land_Tyres_F"
];

// only spawn 1m away from road edges
// and give lower spawn chance
v_cityLamps = [
Land_LampAirport_off_F
Land_LampAirport_F
Land_LampDecor_off_F
Land_LampDecor_F
Land_LampHalogen_off_F
Land_LampHalogen_F
Land_LampHarbour_off_F
Land_LampHarbour_F
Land_LampShabby_off_F
Land_LampShabby_F
Land_LampSolar_off_F
Land_LampSolar_F
Land_LampStadium_F
Land_LampStreet_off_F
Land_LampStreet_F
Land_LampStreet_small_off_F
Land_LampStreet_small_F
];

v_cityDebris = [
Land_Pallet_MilBoxes_F
Land_PaperBox_closed_F
Land_PaperBox_open_empty_F
Land_PaperBox_open_full_F
Land_PhoneBooth_01_F // only near building and roads
Land_PhoneBooth_02_F // only near buildings and roads
];

v_villageDebris = [
Land_Basket_F
Land_Cages_F
Land_CratesPlastic_F
Land_CratesShabby_F
Land_CratesWooden_F
Land_MarketShelter_F
Land_Sack_F
Land_Sacks_goods_F
Land_Sacks_heap_F
Land_StallWater_F
Land_WoodenCart_F
];

v_docks = [
Land_CargoBox_V1_F
Land_Cargo20_blue_F
Land_Cargo20_brick_red_F
Land_Cargo20_cyan_F
Land_Cargo20_grey_F
Land_Cargo20_light_blue_F
Land_Cargo20_light_green_F
Land_Cargo20_military_green_F
Land_Cargo20_orange_F
Land_Cargo20_red_F
Land_Cargo20_sand_F
Land_Cargo20_white_F
Land_Cargo20_yellow_F
Land_Cargo40_blue_F
Land_Cargo40_brick_red_F
Land_Cargo40_cyan_F
Land_Cargo40_grey_F
Land_Cargo40_light_blue_F
Land_Cargo40_light_green_F
Land_Cargo40_military_green_F
Land_Cargo40_orange_F
Land_Cargo40_red_F
Land_Cargo40_sand_F
Land_Cargo40_white_F
Land_Cargo40_yellow_F
Land_Cargo20_color_V1_ruins_F
Land_Cargo20_color_V2_ruins_F
Land_Cargo20_color_V3_ruins_F
Land_Cargo20_china_color_V1_ruins_F
Land_Cargo20_china_color_V2_ruins_F
Land_Cargo20_military_ruins_F
Land_Cargo40_color_V1_ruins_F
Land_Cargo40_color_V2_ruins_F
Land_Cargo40_color_V3_ruins_F
Land_Cargo40_china_color_V1_ruins_F
Land_Cargo40_china_color_V2_ruins_F
Land_Cargo40_military_ruins_F
];

v_gasStation = [
Land_PhoneBooth_01_F // only near building
Land_PhoneBooth_02_F // only near building
Land_fs_feed_F
Land_fs_price_F
Land_fs_roof_F
Land_fs_sign_F
Land_FuelStation_Build_ruins_F
Land_FuelStation_Build_F
Land_FuelStation_Feed_F
Land_FuelStation_Shed_ruins_F
Land_FuelStation_Shed_F
Land_FuelStation_Sign_F
Land_Tank_rust_F
];

v_radar = [
Land_Radar_ruins_F
Land_Radar_F
Land_Radar_Small_ruins_F
Land_Radar_Small_F
];

v_radio = [
Land_Communication_anchor_F
Land_Communication_F
Land_TBox_ruins_F
Land_TBox_F
Land_TTowerBig_1_ruins_F
Land_TTowerBig_1_F
Land_TTowerBig_2_ruins_F
Land_TTowerBig_2_F
Land_TTowerSmall_1_F
Land_TTowerSmall_2_F
];

v_machineShop = [
Land_CarService_F
];

v_powerPlant = [
Land_SolarPanel_1_F
Land_SolarPanel_2_F
Land_SolarPanel_3_F
Land_spp_Mirror_ruins_F
Land_spp_Mirror_Broken_F
Land_spp_Mirror_F
Land_spp_Panel_Broken_F
Land_spp_Panel_F
Land_spp_Tower_ruins_F
Land_spp_Tower_F
Land_spp_Tower_dam_F
Land_spp_Transformer_ruins_F
Land_spp_Transformer_F
];

v_industrial_s = [
Land_GarbageContainer_closed_F
Land_GarbageContainer_open_F
Land_PowerGenerator_F
Land_BottlePlastic_V1_F
Land_Can_Dented_F
Land_Can_Rusty_F
Land_Can_V1_F
Land_Can_V2_F
Land_Can_V3_F
Land_TacticalBacon_F
Land_DrillAku_F
Land_DustMask_F
Land_File_F
Land_Gloves_F
Land_Grinder_F
Land_Hammer_F
Land_Meter3m_F
Land_MultiMeter_F
Land_Pliers_F
Land_Saw_F
Land_Screwdriver_V1_F
Land_Screwdriver_V2_F
Land_Wrench_F
Land_BarrelEmpty_F
Land_BarrelSand_F
Land_BarrelTrash_F
Land_BarrelWater_F
Land_Bucket_F
Land_Bucket_clean_F
Land_Bucket_painted_F
Land_BucketNavy_F
Land_CanisterFuel_F
Land_CanisterOil_F
Land_CanisterPlastic_F
Land_MetalBarrel_empty_F
MetalBarrel_burning_F
Land_MetalBarrel_F
Land_WaterBarrel_F
Land_WaterTank_F
];

v_industrial_m = [
Land_Communication_anchor_F
Land_Communication_F
Land_TBox_ruins_F
Land_TBox_F
Land_Tank_rust_F
Land_ReservoirTank_Airport_ruins_F
Land_ReservoirTank_Airport_F
Land_ReservoirTank_Rust_ruins_F
Land_ReservoirTank_Rust_F
Land_ReservoirTank_V1_ruins_F
Land_ReservoirTank_V1_F
Land_ReservoirTower_ruins_F
Land_ReservoirTower_F
Land_HighVoltageColumn_F
Land_HighVoltageColumnWire_F
Land_HighVoltageTower_dam_F
Land_HighVoltageTower_F
Land_HighVoltageTower_large_F
Land_HighVoltageTower_largeCorner_F
Land_PowerCable_submarine_F
Land_PowerLine_distributor_F
Land_PowerLine_part_F
Land_PowerPoleConcrete_F
Land_PowerPoleWooden_F
Land_PowerPoleWooden_L_off_F
Land_PowerPoleWooden_L_F
Land_PowerPoleWooden_small_F
Land_PowerWireBig_direct_F
Land_PowerWireBig_direct_short_F
Land_PowerWireBig_end_F
Land_PowerWireBig_left_F
Land_PowerWireBig_right_F
Land_PowerWireSmall_damaged_F
Land_PowerWireSmall_direct_F
Land_PowerWireSmall_Left_F
Land_PowerWireSmall_Right_F
Land_PowLines_Transformer_F
Land_IndPipe1_20m_F // Land_IndPipe* might need (alot) of help connecting together, spawn indiv?
Land_IndPipe1_90degL_F
Land_IndPipe1_90degR_F
Land_IndPipe1_ground_F
Land_IndPipe1_Uup_F
Land_IndPipe1_valve_F
Land_IndPipe2_big_9_F
Land_IndPipe2_big_18_F
Land_IndPipe2_big_18ladder_F
Land_IndPipe2_big_ground1_F
Land_IndPipe2_big_ground2_F
Land_IndPipe2_big_support_F
Land_IndPipe2_bigL_L_F
Land_IndPipe2_bigL_R_F
Land_IndPipe2_Small_9_F
Land_IndPipe2_Small_ground1_F
Land_IndPipe2_Small_ground2_F
Land_IndPipe2_SmallL_L_F
Land_IndPipe2_SmallL_R_F
Land_Factory_Conv1_10_ruins_F
Land_Factory_Conv1_10_F
Land_Factory_Conv1_End_F
Land_Factory_Conv1_Main_ruins_F
Land_Factory_Conv1_Main_F
Land_Factory_Conv2_ruins_F
Land_Factory_Conv2_F
Land_Factory_Hopper_ruins_F
Land_Factory_Hopper_F
Land_Factory_Tunnel_F
Land_cmp_Hopper_ruins_F
Land_cmp_Hopper_F
Land_cmp_Shed_ruins_F
Land_cmp_Shed_F
Land_cmp_Shed_dam_F
Land_cmp_Tower_ruins_F
Land_cmp_Tower_F
];

v_industrial_l = [
Land_TTowerBig_1_ruins_F
Land_TTowerBig_1_F
Land_TTowerBig_2_ruins_F
Land_TTowerBig_2_F
Land_TTowerSmall_1_F
Land_TTowerSmall_2_F
Land_Shed_Big_ruins_F
Land_Shed_Big_F
Land_Shed_Small_ruins_F
Land_Shed_Small_F
Land_Shed_Ind_ruins_F
Land_i_Shed_Ind_F
Land_u_Shed_Ind_F
Land_dp_bigTank_ruins_F
Land_dp_bigTank_F
Land_dp_mainFactory_F
Land_dp_smallFactory_F
Land_dp_smallTank_ruins_F
Land_dp_smallTank_F
Land_dp_transformer_F
Land_Factory_Main_ruins_F
Land_Factory_Main_F
];

// will need alot of rules to ensure logical placement
v_barricades = [
Land_Ancient_Wall_4m_F
Land_Ancient_Wall_8m_F
Land_BarGate_F
Land_Canal_Wall_10m_F
Land_Canal_Wall_D_center_F
Land_Canal_Wall_D_left_F
Land_Canal_Wall_D_right_F
Land_Canal_Wall_Stairs_F
Land_Canal_WallSmall_10m_F
Land_City_4m_F
Land_City_8m_F
Land_City_8mD_F
Land_City_Gate_F
Land_City_Pillar_F
Land_City2_4m_F
Land_City2_8m_F
Land_City2_8mD_F
Land_City2_PillarD_F
Land_CncBarrier_F
Land_CncBarrier_stripes_F
Land_CncBarrierMedium_F
Land_CncBarrierMedium4_F
Land_CncShelter_F
Land_CncWall1_F
Land_CncWall4_F
Land_Concrete_SmallWall_4m_F
Land_Concrete_SmallWall_8m_F
Land_Crash_barrier_F
Land_IndFnc_3_D_F
Land_IndFnc_3_F
Land_IndFnc_3_Hole_F
Land_IndFnc_9_F
Land_IndFnc_Corner_F
Land_IndFnc_Pole_F
Land_Mil_ConcreteWall_F
Land_Mil_WallBig_4m_F
Land_Mil_WallBig_Corner_F
Land_Mil_WallBig_Gate_F
Land_Mil_WiredFence_F
Land_Mil_WiredFence_Gate_F
Land_Mil_WiredFenceD_F
Land_Mound01_8m_F
Land_Mound02_8m_F
Land_Net_Fence_4m_F
Land_Net_Fence_8m_F
Land_Net_Fence_Gate_F
Land_Net_Fence_pole_F
Land_Net_FenceD_8m_F
Land_New_WiredFence_5m_F
Land_New_WiredFence_10m_Dam_F
Land_New_WiredFence_10m_F
Land_New_WiredFence_pole_F
Land_Pipe_fence_4m_F
Land_Pipe_fence_4mNoLC_F
Land_PipeWall_concretel_8m_F
Land_Rampart_F
Land_RedWhitePole_F
Land_Slums01_8m
Land_Slums01_pole
Land_Slums02_4m
Land_Slums02_pole
Land_SportGround_fence_F
Land_Stone_4m_F
Land_Stone_8m_F
Land_Stone_8mD_F
Land_Stone_Gate_F
Land_Stone_pillar_F
Land_Wall_IndCnc_2deco_F
Land_Wall_IndCnc_4_D_F
Land_Wall_IndCnc_4_F
Land_Wall_IndCnc_End_2_F
Land_Wall_IndCnc_Pole_F
Land_Wall_Tin_4
Land_Wall_Tin_4_2
Land_Wall_Tin_Pole
Land_Wired_Fence_4m_F
Land_Wired_Fence_4mD_F
Land_Wired_Fence_8m_F
Land_Wired_Fence_8mD_F
];

v_militaryNets = [

];

v_militaryBase = [

];

v_militaryOutpost = [
Land_BagBunker_Large_F
Land_BagBunker_Small_F
Land_BagBunker_Tower_F
];

v_militaryCheckpoint = [
Land_BagFence_Corner_F
Land_BagFence_End_F
Land_BagFence_Long_F
Land_BagFence_Round_F
Land_BagFence_Short_F
];

v_rural = [
Land_cargo_addon01_V1_F
Land_cargo_addon01_V2_F
Land_cargo_addon02_V1_F
Land_cargo_addon02_V2_F
Land_cargo_house_slum_ruins_F
Land_cargo_house_slum_F
Land_Slum_House01_ruins_F
Land_Slum_House01_F
Land_Slum_House02_ruins_F
Land_Slum_House02_F
Land_Slum_House03_ruins_F
Land_Slum_House03_F
];

v_desert = [

];

v_village = [

];

v_fencesRural = [

];

v_fencesIndustrial = [

];

v_warzone = [

];
